### PR TITLE
resolves#19

### LINKED ISSUE #19: Docker issues
I'm new to Docker (not to PHP) so apologies if I'm missing something obvious.
Steps:

1. `docker-compose up` [wait for it to complete]
2. Navigate to http://localhost:8080/
3. Error: `Fatal error: require_once(): Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/index.php on line 9`
4. I also tried a `docker-compose build` before the `docker-compose up` but that gave the same result.

I was expecting to see the quickstart. Am I doing something wrong?
Any assistance greatly appreciated.

### PR DESCRIPTION
**Pull request by webfoolery**
I've incorporated the `composer install` into the Dockerfile so that users don't need to go in & run it manually. 
Resolves #19

### CODE REVIEW

**Comment by meihDS** [comment]
I tested this in branch and I still had to run composer install. I'm not sure if I missed a step somewhere. Please lmk if it works for you, Aaron.

**Comment by AaronWDS** [comment]
> I tested this in branch and I still had to run composer install. I'm not sure if I missed a step somewhere. Please lmk if it works for you, Aaron.

Same, I was unable to get composer install working from running `docker-compose up -d`.

**Comment by webfoolery** [comment]
Ahh sorry. I'm getting that too now. I think I left the older image in place where I'd previously run the composer install manually & it was picking that up. 

This one does add the composer dependencies because of the changed in the `Dockerfile`, but I think it gets overwritten when the volumes are created in the `docker-compose.yml` file. I've tried a few things but not cracked it yet.

Ultimately I'm aiming for a user to clone the repo, run docker-compose up and have everything working. If I achieve that I'll let you know.

**Comment by AaronWDS** [comment]
I'll close this for now. Please submit another PR if you come around to figuring it out.  [I'm pretty certain that this is the answer](https://stackoverflow.com/a/46792094/2226328), I just haven't gotten a chance to try it yet, if you're interested.

**Pull request closed without merging**
